# Generated by Django 4.0 on 2022-10-21 13:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bizhaqimizda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='IjtimoitarmoqModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_mail', models.CharField(max_length=50)),
                ('tel_raqam1', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_raqam2', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'ijtimoitarmoq',
                'verbose_name_plural': 'ijtimoitarmoqlar',
            },
        ),
        migrations.CreateModel(
            name='TelefonlarModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('oyiga', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'telefon',
                'verbose_name_plural': 'telefonlar',
            },
        ),
        migrations.CreateModel(
            name='XususiyatModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor.fields.RichTextField()),
                ('tel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.telefonlarmodels')),
            ],
        ),
        migrations.CreateModel(
            name='XarakteristikaModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joylashuv', models.CharField(max_length=50)),
                ('kredit_12oy', models.CharField(max_length=50)),
                ('kredit_6oy', models.CharField(max_length=50)),
                ('kredit_xujat', models.CharField(max_length=100)),
                ('yetkazib_berish', models.CharField(max_length=50)),
                ('oldindan_tulov', models.CharField(max_length=50)),
                ('tel_raqam1', models.CharField(blank=True, max_length=50, null=True)),
                ('tel_raqam2', models.CharField(blank=True, max_length=50, null=True)),
                ('telefon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.telefonlarmodels')),
            ],
            options={
                'verbose_name': 'Xarakteristika',
                'verbose_name_plural': 'Xarakteristikalar',
            },
        ),
        migrations.CreateModel(
            name='Tel_Rasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='tel_rasmlari')),
                ('telefon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.telefonlarmodels')),
            ],
            options={
                'verbose_name': 'Tel Rasmlari',
            },
        ),
        migrations.CreateModel(
            name='Chegirmalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foizi', models.IntegerField(verbose_name='Chegirma foiz miqdorida')),
                ('telefonlar', models.ManyToManyField(null=True, to='product.TelefonlarModels')),
            ],
            options={
                'verbose_name': 'Chegirmalar',
                'verbose_name_plural': 'Chegirmalar',
            },
        ),
    ]
