# Generated by Django 4.0 on 2022-10-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_tel_rasmlari_rasm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tel_rasmlari',
            name='rasm',
            field=models.ImageField(upload_to='tel_rasmlari'),
        ),
    ]
