# Generated by Django 4.0 on 2022-10-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_tel_rasmlari_rasm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xususiyatmodels',
            name='description',
        ),
        migrations.AddField(
            model_name='xususiyatmodels',
            name='batafsil',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xususiyatmodels',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
