# Generated by Django 4.0 on 2022-10-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_xususiyatmodels_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tel_rasmlari',
            name='rasm',
            field=models.ImageField(upload_to='tel_rasmlari'),
        ),
    ]
